# Generated by Django 3.0.3 on 2020-03-08 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_description_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='item',
        ),
        migrations.AddField(
            model_name='listing',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='pic',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
