# Generated by Django 3.0.3 on 2020-03-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200308_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pic',
            field=models.CharField(max_length=256),
        ),
    ]
