# Generated by Django 3.0.3 on 2020-03-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
