# Generated by Django 3.0.3 on 2020-03-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watching',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watching',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
