# Generated by Django 3.0.3 on 2020-03-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200308_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watching',
            new_name='item',
        ),
    ]
